apiVersion: v1
kind: Service
metadata:
  name: zone-spread-demo
  namespace: kyverno-ha-demo
  labels:
    app: zone-spread-demo
spec:
  clusterIP: None
  selector:
    app: zone-spread-demo
    ha-zone-spread: "enabled"
