apiVersion: v1
kind: Secret
metadata:
  name: keda-jetstream-trigger
  namespace: nats-jetstream-keda
type: Opaque
stringData:
  endpoint: nats.nats-jetstream-keda.svc.cluster.local:8222
  account: $G
