apiVersion: v1
kind: Secret
metadata:
  name: nats-client-credentials
  namespace: nats-jetstream-keda
type: Opaque
stringData:
  NATS_URL: nats://nats.nats-jetstream-keda.svc.cluster.local:4222
  NATS_USER: orders-app
  NATS_PASSWORD: orders-pass
